Repository PrayHelper/Uspray-spring, pull requests merged in 2023-11, with the labels that each got.

#47 Feat/category
  src/main/java/com/uspray/uspray/DTO/category/CategoryRequestDto.java
  src/main/java/com/uspray/uspray/DTO/category/CategoryResponseDto.java
  src/main/java/com/uspray/uspray/DTO/pray/PrayListResponseDto.java
  src/main/java/com/uspray/uspray/DTO/pray/request/PrayRequestDto.java
  src/main/java/com/uspray/uspray/DTO/pray/request/PrayResponseDto.java
  src/main/java/com/uspray/uspray/Enums/PrayType.java
  src/main/java/com/uspray/uspray/InitDb.java
  src/main/java/com/uspray/uspray/controller/AuthController.java
  src/main/java/com/uspray/uspray/controller/CategoryController.java
  src/main/java/com/uspray/uspray/controller/FCMController.java
  src/main/java/com/uspray/uspray/controller/PrayController.java
  src/main/java/com/uspray/uspray/controller/ShareController.java
  src/main/java/com/uspray/uspray/controller/SmsController.java
  src/main/java/com/uspray/uspray/domain/Category.java
  src/main/java/com/uspray/uspray/domain/Pray.java
  src/main/java/com/uspray/uspray/exception/ErrorStatus.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
  src/main/java/com/uspray/uspray/infrastructure/CategoryRepository.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/PrayRepositoryImpl.java
  src/main/java/com/uspray/uspray/service/AuthService.java
  src/main/java/com/uspray/uspray/service/CategoryService.java
  src/main/java/com/uspray/uspray/service/PrayService.java
Labels: 🚀개발, 🤖수정, 🔔긴급

#48 Modify/#45 encrypt pray description
  src/main/java/com/uspray/uspray/InitDb.java
  src/main/java/com/uspray/uspray/domain/Pray.java
Labels: 🤖수정

#50 Feat/#32 history api
  src/main/java/com/uspray/uspray/DTO/history/response/HistoryDetailResponseDto.java
  src/main/java/com/uspray/uspray/DTO/history/response/HistoryListResponseDto.java
  src/main/java/com/uspray/uspray/DTO/history/response/HistoryResponseDto.java
  src/main/java/com/uspray/uspray/InitDb.java
  src/main/java/com/uspray/uspray/controller/HistoryController.java
  src/main/java/com/uspray/uspray/domain/History.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
  src/main/java/com/uspray/uspray/infrastructure/HistoryRepository.java
  src/main/java/com/uspray/uspray/infrastructure/HistoryRepositoryCustom.java
  src/main/java/com/uspray/uspray/infrastructure/PrayRepository.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/history/HistoryRepositoryImpl.java
  src/main/java/com/uspray/uspray/service/HistoryService.java
  src/main/java/com/uspray/uspray/service/SchedulerService.java
Labels: 🚀개발

#63 Feat/#62 기도제목 수정하기 제약조건 추가
  src/main/java/com/uspray/uspray/DTO/pray/PrayListResponseDto.java
  src/main/java/com/uspray/uspray/DTO/pray/request/PrayUpdateRequestDto.java
  src/main/java/com/uspray/uspray/DTO/pray/response/PrayResponseDto.java
  src/main/java/com/uspray/uspray/DTO/sharedpray/response/SharedPrayListResponseDto.java
  src/main/java/com/uspray/uspray/controller/HistoryController.java
  src/main/java/com/uspray/uspray/controller/PrayController.java
  src/main/java/com/uspray/uspray/controller/ShareController.java
  src/main/java/com/uspray/uspray/domain/Pray.java
  src/main/java/com/uspray/uspray/exception/ErrorStatus.java
  src/main/java/com/uspray/uspray/infrastructure/PrayRepository.java
  src/main/java/com/uspray/uspray/service/PrayFacade.java
  src/main/java/com/uspray/uspray/service/PrayService.java
  src/main/java/com/uspray/uspray/service/SchedulerService.java
Labels: 🚀개발, 🧱구조 변경, 🤖수정

#56 Deploy/#52-deploy-docker-file
  .github/workflows/deploy.dev.yml
  .github/workflows/deploy.dev2.yml
  Dockerfile
Labels: 🛠️설정

#61 Feat/#58 group service
  src/main/java/com/uspray/uspray/DTO/group/request/GroupMemberRequestDto.java
  src/main/java/com/uspray/uspray/DTO/group/request/GroupRequestDto.java
  src/main/java/com/uspray/uspray/DTO/group/response/GroupDetailResponseDto.java
  src/main/java/com/uspray/uspray/DTO/group/response/GroupListResponseDto.java
  src/main/java/com/uspray/uspray/DTO/group/response/GroupResponseDto.java
  src/main/java/com/uspray/uspray/InitDb.java
  src/main/java/com/uspray/uspray/controller/GroupController.java
  src/main/java/com/uspray/uspray/domain/Group.java
  src/main/java/com/uspray/uspray/domain/Member.java
  src/main/java/com/uspray/uspray/exception/ErrorStatus.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
  src/main/java/com/uspray/uspray/infrastructure/GroupRepository.java
  src/main/java/com/uspray/uspray/infrastructure/HistoryRepository.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/group/GroupRepositoryCustom.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/group/GroupRepositoryImpl.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/history/HistoryRepositoryCustom.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/history/HistoryRepositoryImpl.java
  src/main/java/com/uspray/uspray/service/GroupFacadeService.java
  src/main/java/com/uspray/uspray/service/GroupPrayService.java
Labels: 🚀개발

#60 Feat/#51 social
  build.gradle
  src/main/java/com/uspray/uspray/config/SecurityConfig.java
  src/main/java/com/uspray/uspray/controller/AuthController.java
  src/main/java/com/uspray/uspray/domain/Member.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
  src/main/java/com/uspray/uspray/external/client/oauth2/CustomOAuth2User.java
  src/main/java/com/uspray/uspray/external/client/oauth2/CustomOAuth2UserService.java
  src/main/java/com/uspray/uspray/external/client/oauth2/OAuth2LoginFailureHandler.java
  src/main/java/com/uspray/uspray/external/client/oauth2/OAuth2LoginSuccessHandler.java
  src/main/java/com/uspray/uspray/external/client/oauth2/OAuthAttributes.java
  src/main/java/com/uspray/uspray/external/client/oauth2/dto/KakaoOAuth2UserInfo.java
  src/main/java/com/uspray/uspray/external/client/oauth2/dto/NaverOAuth2UserInfo.java
  src/main/java/com/uspray/uspray/external/client/oauth2/dto/OAuth2UserInfo.java
  src/main/java/com/uspray/uspray/infrastructure/MemberRepository.java
Labels: 🛠️설정, 🚀개발

#75 fix: add CORS configurations
  src/main/java/com/uspray/uspray/config/SecurityConfig.java
Labels: 🐞오류, 🛠️설정, 🔔긴급, ✅해결
