Repository PrayHelper/Uspray-spring, pull requests merged in 2023-10, with the labels that each got.

#26 Feat/#23 add notification
  .gitignore
  build.gradle
  src/main/java/com/uspray/uspray/DTO/notification/FCMNotificationRequestDto.java
  src/main/java/com/uspray/uspray/DTO/notification/NotificationAgreeDto.java
  src/main/java/com/uspray/uspray/Enums/NotificationType.java
  src/main/java/com/uspray/uspray/config/SecurityConfig.java
  src/main/java/com/uspray/uspray/controller/AuthController.java
  src/main/java/com/uspray/uspray/controller/FCMController.java
  src/main/java/com/uspray/uspray/controller/MemberController.java
  src/main/java/com/uspray/uspray/domain/FCMMessage.java
  src/main/java/com/uspray/uspray/domain/Member.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
  src/main/java/com/uspray/uspray/infrastructure/MemberRepository.java
  src/main/java/com/uspray/uspray/infrastructure/query/MemberQueryRepository.java
  src/main/java/com/uspray/uspray/service/AuthService.java
  src/main/java/com/uspray/uspray/service/FCMNotificationService.java
  src/main/java/com/uspray/uspray/service/MemberService.java
  src/main/java/com/uspray/uspray/service/SchedulerService.java
Labels: 🛠️설정, 🚀개발, 🧱구조 변경, 🤖수정

#28 Feat: get pray list with sorting
  src/main/java/com/uspray/uspray/DTO/pray/request/PrayRequestDto.java
  src/main/java/com/uspray/uspray/config/QuerydslConfig.java
  src/main/java/com/uspray/uspray/controller/PrayController.java
  src/main/java/com/uspray/uspray/domain/Pray.java
  src/main/java/com/uspray/uspray/infrastructure/PrayRepository.java
  src/main/java/com/uspray/uspray/infrastructure/PrayRepositoryCustom.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/PrayRepositoryImpl.java
  src/main/java/com/uspray/uspray/service/PrayService.java
Labels: 🚀개발, 🤖수정

#35 Feat/#29 member delete
  src/main/java/com/uspray/uspray/DTO/auth/request/MemberDeleteDto.java
  src/main/java/com/uspray/uspray/Enums/WithdrawReason.java
  src/main/java/com/uspray/uspray/controller/AuthController.java
  src/main/java/com/uspray/uspray/domain/Withdraw.java
  src/main/java/com/uspray/uspray/infrastructure/WithdrawRepository.java
  src/main/java/com/uspray/uspray/service/AuthService.java
Labels: 🚀개발, 🤖수정, 🔔긴급

#39 Feat/#34 create dummy
  src/main/java/com/uspray/uspray/InitDb.java
Labels: 🚀개발

#38 Feat/#24 shared pray
  src/main/java/com/uspray/uspray/DTO/sharedpray/request/SharedPrayRequestDto.java
  src/main/java/com/uspray/uspray/DTO/sharedpray/response/SharedPrayListResponseDto.java
  src/main/java/com/uspray/uspray/DTO/sharedpray/response/SharedPrayResponseDto.java
  src/main/java/com/uspray/uspray/controller/MemberController.java
  src/main/java/com/uspray/uspray/controller/ShareController.java
  src/main/java/com/uspray/uspray/domain/Pray.java
  src/main/java/com/uspray/uspray/domain/SharedPray.java
  src/main/java/com/uspray/uspray/exception/ErrorStatus.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
  src/main/java/com/uspray/uspray/infrastructure/MemberRepository.java
  src/main/java/com/uspray/uspray/infrastructure/PrayRepository.java
  src/main/java/com/uspray/uspray/infrastructure/SharedPrayRepository.java
  src/main/java/com/uspray/uspray/jwt/TokenProvider.java
  src/main/java/com/uspray/uspray/service/SchedulerService.java
  src/main/java/com/uspray/uspray/service/ShareService.java
Labels: 🚀개발

#41 Feat/#40 build test CI
  .github/workflows/build-test.yml
Labels: 🛠️설정
