Repository PrayHelper/Uspray-spring, pull requests merged in 2023-09, with the labels that each got.

#3 Feat/#2 create api response dto
  build.gradle
  src/main/java/com/uspray/uspray/common/dto/ApiResponseDto.java
  src/main/java/com/uspray/uspray/exception/ErrorStatus.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
Labels: enhancement

#5 Feat/#4 create member entity
  src/main/java/com/uspray/uspray/UsprayApplication.java
  src/main/java/com/uspray/uspray/common/domain/AuditingTimeEntity.java
  src/main/java/com/uspray/uspray/domain/Member.java
Labels: enhancement

#12 Feat/QueryDSL 설정 추가
  build.gradle
Labels: 🛠️설정

#11 Feat/#10 auth and get info
  src/main/java/com/uspray/uspray/config/swagger/SwaggerConfig.java
  src/main/java/com/uspray/uspray/controller/AuthController.java
  src/main/java/com/uspray/uspray/domain/Member.java
  src/main/java/com/uspray/uspray/exception/ErrorStatus.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
  src/main/java/com/uspray/uspray/exception/model/CustomException.java
  src/main/java/com/uspray/uspray/exception/model/ExistIdException.java
  src/main/java/com/uspray/uspray/exception/model/NotFoundException.java
  src/main/java/com/uspray/uspray/infrastructure/MemberRepository.java
  src/main/java/com/uspray/uspray/service/AuthService.java
  src/main/java/com/uspray/uspray/util/SecurityUtil.java
Labels: 🚀개발

#17 Feat/#16 find idpw
  src/main/java/com/uspray/uspray/DTO/auth/request/FindIdDto.java
  src/main/java/com/uspray/uspray/DTO/auth/request/FindPwDto.java
  src/main/java/com/uspray/uspray/DTO/auth/request/MemberRequestDto.java
  src/main/java/com/uspray/uspray/DTO/auth/response/MemberResponseDto.java
  src/main/java/com/uspray/uspray/controller/AuthController.java
  src/main/java/com/uspray/uspray/domain/Member.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
  src/main/java/com/uspray/uspray/infrastructure/MemberRepository.java
  src/main/java/com/uspray/uspray/service/AuthService.java
Labels: 🚀개발

#19 feat: 전화번호 변경 api 생성
  src/main/java/com/uspray/uspray/controller/MemberController.java
  src/main/java/com/uspray/uspray/domain/Member.java
  src/main/java/com/uspray/uspray/exception/ErrorStatus.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
  src/main/java/com/uspray/uspray/exception/model/CustomException.java
  src/main/java/com/uspray/uspray/infrastructure/MemberRepository.java
  src/main/java/com/uspray/uspray/service/MemberService.java
Labels: 🚀개발

#20 add: exception advice 구현
  src/main/java/com/uspray/uspray/common/advice/ControllerExceptionAdvice.java
  src/main/java/com/uspray/uspray/domain/Member.java
  src/main/java/com/uspray/uspray/exception/ErrorStatus.java
Labels: 🚀개발, 🤖수정

#14 Feat/#13 add sms certification
  build.gradle
  src/main/java/com/uspray/uspray/DTO/sms/CertificationDto.java
  src/main/java/com/uspray/uspray/DTO/sms/MessageDto.java
  src/main/java/com/uspray/uspray/DTO/sms/SmsRequestDto.java
  src/main/java/com/uspray/uspray/DTO/sms/SmsResponseDto.java
  src/main/java/com/uspray/uspray/config/SecurityConfig.java
  src/main/java/com/uspray/uspray/controller/SmsController.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
  src/main/java/com/uspray/uspray/service/SmsService.java
Labels: 🚀개발

#25 Create gradle.yml
  .github/workflows/gradle.yml
Labels: 🛠️설정
