Repository PrayHelper/Uspray-spring, pull requests merged in 2023-12, with the labels that each got.

#71 Refactor: Group API
  src/main/java/com/uspray/uspray/DTO/auth/response/MemberResponseDto.java
  src/main/java/com/uspray/uspray/DTO/group/request/GroupMemberRequestDto.java
  src/main/java/com/uspray/uspray/DTO/group/response/GroupMemberResponseDto.java
  src/main/java/com/uspray/uspray/InitDb.java
  src/main/java/com/uspray/uspray/controller/GroupController.java
  src/main/java/com/uspray/uspray/domain/Group.java
  src/main/java/com/uspray/uspray/domain/GroupMember.java
  src/main/java/com/uspray/uspray/domain/Member.java
  src/main/java/com/uspray/uspray/exception/ErrorStatus.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
  src/main/java/com/uspray/uspray/infrastructure/GroupMemberRepository.java
  src/main/java/com/uspray/uspray/infrastructure/MemberRepository.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/group/GroupRepositoryCustom.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/group/GroupRepositoryImpl.java
  src/main/java/com/uspray/uspray/service/GroupFacade.java
  src/main/java/com/uspray/uspray/service/GroupService.java
  src/main/java/com/uspray/uspray/util/MaskingUtil.java
Labels: 🚀개발, ✅해결

#82 [Refactor] social rename
  src/main/java/com/uspray/uspray/Enums/Authority.java
  src/main/java/com/uspray/uspray/controller/MemberController.java
  src/main/java/com/uspray/uspray/domain/Member.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
  src/main/java/com/uspray/uspray/external/client/oauth2/CustomOAuth2UserService.java
  src/main/java/com/uspray/uspray/external/client/oauth2/OAuth2LoginSuccessHandler.java
  src/main/java/com/uspray/uspray/service/MemberService.java
Labels: 🚀개발, 🤖수정, 🔔긴급

#86 Deploy/#85 deploy deploy workflow ver2
  .github/workflows/deploy.dev2.yml
  build.gradle
  docker-compose.yml
Labels: 🛠️설정, 🚀개발

#81 Refactor/#70 grouppray additional function
  src/main/java/com/uspray/uspray/DTO/grouppray/GroupPrayRequestDto.java
  src/main/java/com/uspray/uspray/DTO/grouppray/GroupPrayResponseDto.java
  src/main/java/com/uspray/uspray/DTO/grouppray/ScrapRequestDto.java
  src/main/java/com/uspray/uspray/InitDb.java
  src/main/java/com/uspray/uspray/controller/GroupPrayController.java
  src/main/java/com/uspray/uspray/domain/Group.java
  src/main/java/com/uspray/uspray/domain/GroupPray.java
  src/main/java/com/uspray/uspray/domain/Member.java
  src/main/java/com/uspray/uspray/domain/Pray.java
  src/main/java/com/uspray/uspray/domain/ScrapAndHeart.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
  src/main/java/com/uspray/uspray/infrastructure/ScrapAndHeartRepository.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/grouppray/GroupPrayRepositoryCustom.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/grouppray/GroupPrayRepositoryImpl.java
  src/main/java/com/uspray/uspray/service/GroupPrayFacade.java
  src/main/java/com/uspray/uspray/service/GroupPrayService.java
Labels: 🚀개발, 🫠요청, 🤖수정, ✅해결

#88 Refactor: Authcontroller error handling
  src/main/java/com/uspray/uspray/controller/AuthController.java
  src/main/java/com/uspray/uspray/exception/ErrorStatus.java
  src/main/java/com/uspray/uspray/service/AuthService.java
Labels: 🤖수정, ✅해결

#90 Refactor: Group API
  src/main/java/com/uspray/uspray/DTO/group/response/GroupResponseDto.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/group/GroupRepositoryImpl.java
  src/main/java/com/uspray/uspray/service/GroupService.java
Labels: ❌삭제, 🤖수정, 🔔긴급

#83 Refactor: Shared Pray
  src/main/java/com/uspray/uspray/DTO/sharedpray/request/SharedPrayDeleteRequestDto.java
  src/main/java/com/uspray/uspray/DTO/sharedpray/request/SharedPrayRequestDto.java
  src/main/java/com/uspray/uspray/DTO/sharedpray/request/SharedPraySaveRequestDto.java
  src/main/java/com/uspray/uspray/DTO/sharedpray/response/SharedPrayListResponseDto.java
  src/main/java/com/uspray/uspray/controller/ShareController.java
  src/main/java/com/uspray/uspray/infrastructure/SharedPrayRepository.java
  src/main/java/com/uspray/uspray/service/ShareFacade.java
  src/main/java/com/uspray/uspray/service/ShareService.java
Labels: 🤖수정

#93 Fix/#92 sms auth
  src/main/java/com/uspray/uspray/controller/SmsController.java
  src/main/java/com/uspray/uspray/exception/ErrorStatus.java
  src/main/java/com/uspray/uspray/service/SmsService.java
Labels: 🚀개발, 🔔긴급, ✅해결

#95 Feat/#94 pw change and check
  src/main/java/com/uspray/uspray/DTO/auth/request/ChangePwDto.java
  src/main/java/com/uspray/uspray/DTO/auth/request/CheckPwDto.java
  src/main/java/com/uspray/uspray/controller/AuthController.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
  src/main/java/com/uspray/uspray/infrastructure/MemberRepository.java
  src/main/java/com/uspray/uspray/service/AuthService.java
  src/main/java/com/uspray/uspray/service/SmsService.java
Labels: 🤖수정, ✅해결

#109 [Refactor]#87 모임 기도제목 이모저모
  src/main/java/com/uspray/uspray/DTO/grouppray/GroupPrayRappingDto.java
  src/main/java/com/uspray/uspray/DTO/grouppray/GroupPrayResponseDto.java
  src/main/java/com/uspray/uspray/DTO/pray/request/PrayToGroupPrayDto.java
  src/main/java/com/uspray/uspray/InitDb.java
  src/main/java/com/uspray/uspray/controller/GroupPrayController.java
  src/main/java/com/uspray/uspray/controller/PrayController.java
  src/main/java/com/uspray/uspray/domain/GroupPray.java
  src/main/java/com/uspray/uspray/domain/Pray.java
  src/main/java/com/uspray/uspray/domain/ScrapAndHeart.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
  src/main/java/com/uspray/uspray/infrastructure/GroupPrayRepository.java
  src/main/java/com/uspray/uspray/infrastructure/PrayRepository.java
  src/main/java/com/uspray/uspray/infrastructure/ScrapAndHeartRepository.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/grouppray/GroupPrayRepositoryCustom.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/grouppray/GroupPrayRepositoryImpl.java
  src/main/java/com/uspray/uspray/service/GroupPrayFacade.java
  src/main/java/com/uspray/uspray/service/PrayFacade.java
  src/main/java/com/uspray/uspray/service/PrayService.java
Labels: 🚀개발, 🤖수정, 🔔긴급, ✅해결

#108 feat: 공유한 기도제목의 작성자 이름 표시 추가
  src/main/java/com/uspray/uspray/DTO/history/request/HistoryRequestDto.java
  src/main/java/com/uspray/uspray/DTO/history/response/HistoryResponseDto.java
  src/main/java/com/uspray/uspray/DTO/pray/response/PrayResponseDto.java
  src/main/java/com/uspray/uspray/InitDb.java
  src/main/java/com/uspray/uspray/controller/HistoryController.java
  src/main/java/com/uspray/uspray/domain/Group.java
  src/main/java/com/uspray/uspray/domain/History.java
  src/main/java/com/uspray/uspray/exception/ErrorStatus.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/history/HistoryRepositoryImpl.java
  src/main/java/com/uspray/uspray/service/HistoryService.java
  src/main/java/com/uspray/uspray/service/PrayService.java
Labels: 🚀개발, ✅해결

#114 modify: 공유기도제목 저장시 deadline 설정 추가
  src/main/java/com/uspray/uspray/DTO/sharedpray/request/SharedPraySaveRequestDto.java
  src/main/java/com/uspray/uspray/service/ShareFacade.java
Labels: 🤖수정

#113 feat: add category type
  src/main/java/com/uspray/uspray/DTO/category/CategoryRequestDto.java
  src/main/java/com/uspray/uspray/Enums/CategoryType.java
  src/main/java/com/uspray/uspray/InitDb.java
  src/main/java/com/uspray/uspray/controller/CategoryController.java
  src/main/java/com/uspray/uspray/domain/Category.java
  src/main/java/com/uspray/uspray/exception/ErrorStatus.java
  src/main/java/com/uspray/uspray/infrastructure/CategoryRepository.java
  src/main/java/com/uspray/uspray/service/CategoryService.java
  src/main/java/com/uspray/uspray/service/PrayFacade.java
  src/main/java/com/uspray/uspray/service/ShareFacade.java
Labels: 🚀개발, 🧱구조 변경, 🤖수정
