Repository PrayHelper/Uspray-spring, pull requests merged in 2024-01, with the labels that each got.

#116 Refactor/#115 fix pw func and grouppray
  src/main/java/com/uspray/uspray/DTO/auth/request/CheckPwDTO.java
  src/main/java/com/uspray/uspray/DTO/auth/request/FindPwDTO.java
  src/main/java/com/uspray/uspray/controller/AuthController.java
  src/main/java/com/uspray/uspray/controller/MemberController.java
  src/main/java/com/uspray/uspray/domain/GroupPray.java
  src/main/java/com/uspray/uspray/domain/Pray.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
  src/main/java/com/uspray/uspray/service/AuthService.java
  src/main/java/com/uspray/uspray/service/MemberService.java
  src/main/java/com/uspray/uspray/service/PrayFacade.java
Labels: 🚀개발, 🤖수정, ✅해결

#117 feat: add category color
  src/main/java/com/uspray/uspray/DTO/pray/PrayListResponseDto.java
  src/main/java/com/uspray/uspray/service/PrayFacade.java
  src/main/java/com/uspray/uspray/service/PrayService.java
Labels: 🚀개발, 🤖수정

#120 [fix] history에 Category 관련해서 버그 수정 최적화
  src/main/java/com/uspray/uspray/DTO/history/response/HistoryDetailResponseDto.java
  src/main/java/com/uspray/uspray/DTO/history/response/HistoryResponseDto.java
  src/main/java/com/uspray/uspray/controller/HistoryController.java
  src/main/java/com/uspray/uspray/domain/History.java
  src/main/java/com/uspray/uspray/infrastructure/HistoryRepository.java
  src/main/java/com/uspray/uspray/infrastructure/PrayRepository.java
  src/main/java/com/uspray/uspray/service/CategoryService.java
  src/main/java/com/uspray/uspray/service/PrayFacade.java
Labels: ✅해결

#121 fix: category order error
  src/main/java/com/uspray/uspray/service/CategoryService.java
Labels: 🔔긴급

#122 Fix/pray errors
  src/main/java/com/uspray/uspray/InitDb.java
  src/main/java/com/uspray/uspray/controller/CategoryController.java
  src/main/java/com/uspray/uspray/service/CategoryService.java
Labels: 🤖수정

#124 feat: make total_count in history
  src/main/java/com/uspray/uspray/DTO/history/response/HistoryDetailResponseDto.java
  src/main/java/com/uspray/uspray/DTO/history/response/HistoryResponseDto.java
  src/main/java/com/uspray/uspray/domain/History.java
  src/main/java/com/uspray/uspray/domain/Pray.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/pray/PrayRepositoryCustom.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/pray/PrayRepositoryImpl.java
  src/main/java/com/uspray/uspray/service/PrayFacade.java
Labels: 🚀개발

#126 Feat/member check pw
  src/main/java/com/uspray/uspray/DTO/category/CategoryRequestDto.java
  src/main/java/com/uspray/uspray/controller/AuthController.java
  src/main/java/com/uspray/uspray/controller/MemberController.java
  src/main/java/com/uspray/uspray/infrastructure/CategoryRepository.java
  src/main/java/com/uspray/uspray/service/CategoryService.java
  src/main/java/com/uspray/uspray/service/MemberService.java
  src/main/java/com/uspray/uspray/service/PrayFacade.java
Labels: 🐞오류, 🚀개발, ✅해결

#128 Fix/notification setting
  src/main/java/com/uspray/uspray/DTO/pray/response/PrayResponseDto.java
  src/main/java/com/uspray/uspray/domain/Member.java
  src/main/java/com/uspray/uspray/service/PrayFacade.java
  src/main/java/com/uspray/uspray/service/ShareFacade.java
Labels: 🚀개발
