Repository PrayHelper/Uspray-spring, pull requests merged in 2024-02, with the labels that each got.

#132 Refactor: /share/receive API
  src/main/java/com/uspray/uspray/controller/ShareController.java
  src/main/java/com/uspray/uspray/exception/ErrorStatus.java
  src/main/java/com/uspray/uspray/infrastructure/PrayRepository.java
  src/main/java/com/uspray/uspray/infrastructure/SharedPrayRepository.java
  src/main/java/com/uspray/uspray/service/ShareFacade.java
Labels: 🔔긴급, ✅해결

#136 Fix/#135 group pray edge case
  src/main/java/com/uspray/uspray/DTO/pray/response/PrayResponseDto.java
  src/main/java/com/uspray/uspray/controller/GroupPrayController.java
  src/main/java/com/uspray/uspray/controller/PrayController.java
  src/main/java/com/uspray/uspray/exception/ErrorStatus.java
  src/main/java/com/uspray/uspray/infrastructure/GroupPrayRepository.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/category/CategoryRepositoryCustom.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/category/CategoryRepositoryImpl.java
  src/main/java/com/uspray/uspray/service/GroupPrayFacade.java
  src/main/java/com/uspray/uspray/service/PrayFacade.java
Labels: 🚀개발, 🤖수정, ✅해결

#137 feat: 일반, 소셜 로그인 체크 API
  src/main/java/com/uspray/uspray/DTO/auth/response/LoginTypeResponseDto.java
  src/main/java/com/uspray/uspray/controller/AuthController.java
  src/main/java/com/uspray/uspray/exception/SuccessStatus.java
  src/main/java/com/uspray/uspray/service/AuthService.java
Labels: 🚀개발, 🔔긴급

#138 deploy: database migration
  build.gradle
  src/main/java/com/uspray/uspray/DTO/history/response/HistoryDetailResponseDto.java
  src/main/java/com/uspray/uspray/DTO/sharedpray/response/SharedPrayResponseDto.java
  src/main/java/com/uspray/uspray/InitDb.java
  src/main/java/com/uspray/uspray/config/SecurityConfig.java
  src/main/java/com/uspray/uspray/config/sql/UserQueries.java
  src/main/java/com/uspray/uspray/config/sql/category.sql
  src/main/java/com/uspray/uspray/config/sql/changePrimaryKey.sql
  src/main/java/com/uspray/uspray/config/sql/group.sql
  src/main/java/com/uspray/uspray/config/sql/history.sql
  src/main/java/com/uspray/uspray/config/sql/pray.sql
  src/main/java/com/uspray/uspray/config/sql/sharedPray.sql
  src/main/java/com/uspray/uspray/config/sql/user.sql
  src/main/java/com/uspray/uspray/domain/History.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/category/CategoryRepositoryImpl.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/history/HistoryRepositoryImpl.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/pray/PrayRepositoryImpl.java
  src/main/java/com/uspray/uspray/service/GroupPrayFacade.java
  src/main/java/com/uspray/uspray/service/HistoryService.java
  src/main/java/com/uspray/uspray/service/PrayFacade.java
  uspray_dump.sql
Labels: 🛠️설정, 🚀개발, ❗위험, 🔔긴급

#143 Fix/#142 fix group grouppray
  src/main/java/com/uspray/uspray/DTO/group/response/GroupResponseDto.java
  src/main/java/com/uspray/uspray/DTO/grouppray/GroupPrayResponseDto.java
  src/main/java/com/uspray/uspray/DTO/pray/response/PrayResponseDto.java
  src/main/java/com/uspray/uspray/InitDb.java
  src/main/java/com/uspray/uspray/domain/Pray.java
  src/main/java/com/uspray/uspray/infrastructure/GroupPrayRepository.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/category/CategoryRepositoryImpl.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/group/GroupRepositoryImpl.java
  src/main/java/com/uspray/uspray/service/GroupService.java
Labels: 🤖수정, ✅해결

#145 fix: group prayerror
  src/main/java/com/uspray/uspray/DTO/grouppray/GroupPrayResponseDto.java
  src/main/java/com/uspray/uspray/domain/ScrapAndHeart.java
  src/main/java/com/uspray/uspray/infrastructure/ScrapAndHeartRepository.java
  src/main/java/com/uspray/uspray/service/GroupPrayFacade.java
  src/main/java/com/uspray/uspray/service/MemberService.java
  src/main/java/com/uspray/uspray/service/PrayFacade.java
Labels: 🐞오류, ✅해결
