Repository PrayHelper/Uspray-spring, pull requests merged in 2024-04, with the labels that each got.

#163 [FIX] history 생성시 원본 기도의 시작 날짜를 보관하는 필드 추가 및 불러오는 기능 수정
  src/main/java/com/uspray/uspray/DTO/history/response/HistoryDetailResponseDto.java
  src/main/java/com/uspray/uspray/DTO/history/response/HistoryResponseDto.java
  src/main/java/com/uspray/uspray/DTO/pray/request/PrayRequestDto.java
  src/main/java/com/uspray/uspray/InitDb.java
  src/main/java/com/uspray/uspray/controller/HistoryController.java
  src/main/java/com/uspray/uspray/domain/History.java
  src/main/java/com/uspray/uspray/domain/Pray.java
  src/main/java/com/uspray/uspray/infrastructure/CategoryRepository.java
  src/main/java/com/uspray/uspray/infrastructure/HistoryRepository.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/history/HistoryRepositoryImpl.java
  src/main/java/com/uspray/uspray/service/HistoryFacade.java
  src/main/java/com/uspray/uspray/service/HistoryService.java
  src/main/java/com/uspray/uspray/service/PrayFacade.java
Labels: 🤖수정, ✅해결

#165 Fix/push notification re
  src/main/java/com/uspray/uspray/service/PrayFacade.java
  src/main/java/com/uspray/uspray/service/ShareFacade.java
Labels: 🫠요청

#170 feat: 그룹 기도제목 기도 / 스크랩 시에 알림 발송 추가
  src/main/java/com/uspray/uspray/controller/GroupController.java
  src/main/java/com/uspray/uspray/controller/GroupPrayController.java
  src/main/java/com/uspray/uspray/controller/HistoryController.java
  src/main/java/com/uspray/uspray/controller/PrayController.java
  src/main/java/com/uspray/uspray/controller/ShareController.java
  src/main/java/com/uspray/uspray/infrastructure/GroupMemberRepository.java
  src/main/java/com/uspray/uspray/service/CategoryService.java
  src/main/java/com/uspray/uspray/service/SchedulerService.java
  src/main/java/com/uspray/uspray/service/facade/GroupFacade.java
  src/main/java/com/uspray/uspray/service/facade/GroupPrayFacade.java
  src/main/java/com/uspray/uspray/service/facade/HistoryFacade.java
  src/main/java/com/uspray/uspray/service/facade/PrayFacade.java
  src/main/java/com/uspray/uspray/service/facade/ShareFacade.java
Labels: 🚀개발

#172 Fix/#171 fix history detail
  src/main/java/com/uspray/uspray/domain/Group.java
  src/main/java/com/uspray/uspray/domain/Pray.java
  src/main/java/com/uspray/uspray/exception/ErrorStatus.java
  src/main/java/com/uspray/uspray/exception/model/CustomException.java
  src/main/java/com/uspray/uspray/exception/model/ExistIdException.java
  src/main/java/com/uspray/uspray/exception/model/NotFoundException.java
  src/main/java/com/uspray/uspray/exception/model/TokenNotValidException.java
  src/main/java/com/uspray/uspray/infrastructure/CategoryRepository.java
  src/main/java/com/uspray/uspray/infrastructure/GroupMemberRepository.java
  src/main/java/com/uspray/uspray/infrastructure/GroupPrayRepository.java
  src/main/java/com/uspray/uspray/infrastructure/GroupRepository.java
  src/main/java/com/uspray/uspray/infrastructure/HistoryRepository.java
  src/main/java/com/uspray/uspray/infrastructure/MemberRepository.java
  src/main/java/com/uspray/uspray/infrastructure/PrayRepository.java
  src/main/java/com/uspray/uspray/infrastructure/SharedPrayRepository.java
  src/main/java/com/uspray/uspray/infrastructure/querydsl/category/CategoryRepositoryImpl.java
  src/main/java/com/uspray/uspray/service/AuthService.java
  src/main/java/com/uspray/uspray/service/CategoryService.java
  src/main/java/com/uspray/uspray/service/HistoryService.java
  src/main/java/com/uspray/uspray/service/MemberService.java
  src/main/java/com/uspray/uspray/service/SmsService.java
  src/main/java/com/uspray/uspray/service/facade/GroupFacade.java
  src/main/java/com/uspray/uspray/service/facade/GroupPrayFacade.java
  src/main/java/com/uspray/uspray/service/facade/PrayFacade.java
  src/main/java/com/uspray/uspray/service/facade/ShareFacade.java
Labels: 🐞오류, 🤖수정, ✅해결
